### ISSUE TITLE
關於M80Label沒有顯示的問題

### ISSUE THREAD

**Issue by Kidding2651** [xiangwangfeng/M80AttributedLabel#16]
你好，想請教一個問題  (iphone5 環境ios7.0/ios8.0)   我試著使用M80Label來實作聊天室訊息，發現如果有許多訊息傳入，需要同時間產生二個以上的M80Label，其中某個Label的字(純文字無圖)就會顯示不出來，有下Log檢查送進Label的文字.Label的Frame.Label的superview都是沒有問題的，跟TableViewCel的reuse也沒有關係，因為每個Label都有唯一的key來Cache，請問作者能否提供一些方向來解決這個問題

**Comment by xiangwangfeng** [comment]
最好能够有demo提供方便我检查问题

**Comment by jiulin** [comment]
你好！ 最近在写一款阿拉伯产品，发现M80Label，并不支持类似于阿拉伯语从右向左现实的语言，图文混排容易发生错乱。请问作者能提供一些解决方案么？

**Comment by kingsNow** [comment]
Thank you for the authors provide open source.
