### ISSUE TITLE
表情在行末尾时高度计算有误差

### ISSUE THREAD

**Issue by Fairtoys** [xiangwangfeng/M80AttributedLabel#19]
表情在行末尾时高度计算有误差

[self appendImage:image
                          maxSize:CGSizeMake(36,    36)
                           margin:UIEdgeInsetsMake(0, 0, -6, 0)
                        alignment:M80ImageAlignmentBottom];

![screenshot_20150709134714](https://cloud.githubusercontent.com/assets/8790986/8588788/10751508-2641-11e5-849c-7ba22e9f525f.png)

**Comment by Fairtoys** [comment]
控件的宽度为屏幕宽度减20

**Comment by z234009184** [comment]
同样的问题
