### ISSUE TITLE
有个 BUG  删除 - (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event 就好了

### ISSUE THREAD

**Issue by lichory** [xiangwangfeng/M80AttributedLabel#22]
连续初始化 两个 Label 的时候 ，第一个label的 链接点击 总是被第二个 touchbegain给捕获到了 ，不知道是为什么 。

**Comment by lichory** [comment]
删除 - (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event 就好了

**Comment by xiangwangfeng** [comment]
和 https://github.com/xiangwangfeng/M80AttributedLabel/issues/23 重复
