### ISSUE TITLE
如果文字能加上 shadow 就好了

### ISSUE THREAD

**Issue by YueLiXing** [xiangwangfeng/M80AttributedLabel#25]
`
    [showStr addAttributes:@{
                            NSShadowAttributeName: self.shadow,
                            NSVerticalGlyphFormAttributeName: @0,
                            } range:NSMakeRange(0, showStr.length)];
`
写在这里面的阴影显示不出来....

**Comment by xiangwangfeng** [comment]
已添加，但是由于实现的问题，添加的是全局shadow [https://github.com/xiangwangfeng/M80AttributedLabel/commit/766652fc88170aeaf486b35ae722343d2163e016](url)
