### ISSUE TITLE
A issues for detecting URL

### ISSUE THREAD

**Issue by Scyano** [xiangwangfeng/M80AttributedLabel#29]
See this codes in M80AttributedLabel.m=> -  (void)computeLink:sync:, at about line 1,000.
As i know,  you wanna put the detecting at a subthread while the detected string's length is over 50, but i saw the code below, the comments are my query.

`
   // sync to main thread?
   dispatch_sync(get_m80_attributed_label_parse_queue(), ^{

            // Does this time-consuming operation in main thread might not what you wanna do.
            NSArray *links = [M80AttributedLabelURL detectLinks:text];

            // it's just specify a low priority to the following codes, and make the main thread 
            // execute the codes in it's  idle time? I really do not get your point~
            dispatch_async(dispatch_get_main_queue(), ^{ 
                NSString *plainText = [[weakSelf attributedString] string]; 
                if ([plainText isEqualToString:text])  {
                    block(links);
                }
            }
`
Thanks for your sharing~

**Comment by xiangwangfeng** [comment]
It's a mistake that I should async to detecting thread rather than sync to it. The
current code will block the main thread。
https://github.com/xiangwangfeng/M80AttributedLabel/commit/e6cba999f02fe62f0d54d66a8193faf5c36c23de
