### ISSUE TITLE
  超链接的检测可以换成用系统的

### ISSUE THREAD

**Issue by include11** [xiangwangfeng/M80AttributedLabel#36]
https://www.jianshu.com/p/bf302b3df743

**Comment by ZacharyIcoder** [comment]
可以换成这种更好  static NSString *M80URLExpression = @"((http[s]{0,1}|ftp)://[a-zA-Z0-9\\.\\-]+\\.([a-zA-Z]{2,4})(:\\d+)?(/[a-zA-Z0-9\\.\\-~!@#$%^&*+?:_/=<>]*)?)|(www.[a-zA-Z0-9\\.\\-]+\\.([a-zA-Z]{2,4})(:\\d+)?(/[a-zA-Z0-9\\.\\-~!@#$%^&*+?:_/=<>]*)?)";

**Comment by xiangwangfeng** [comment]
可以通过 [M80AttributedLabel setCustomDetectMethod:] 任意替换
