### ISSUE TITLE
单行文本取字体高度不显示问题

### ISSUE THREAD

**Issue by liunianhuaguoyanxi** [xiangwangfeng/M80AttributedLabel#39]
举个很简单的例子：
以下不会显示文本
    NSString *text  = @"The game ";
    M80AttributedLabel *label = [[M80AttributedLabel alloc]initWithFrame:CGRectMake(100, 200, 100, [UIFont systemFontOfSize:14].lineHeight)];
    label.text      = text;
    label.font = [UIFont systemFontOfSize:14];
    [self.view addSubview:label];

而系统的正常显示
    NSString *text  = @"The game ";
    UILabel *label = [[UILabel alloc]initWithFrame:CGRectMake(100, 200, 100, [UIFont systemFontOfSize:14].lineHeight)];
    label.text      = text;
    label.font = [UIFont systemFontOfSize:14];
    [self.view addSubview:label];

希望优化下

**Comment by xiangwangfeng** [comment]
因为内部绘制方式和 UILabel 不一样，导致无法直接使用 fontHeight 来作为高度
可以使用 sizeThatFits: 来计算真实的高度
或者取巧做法在 fontHeight 后面加上一个像素 height = fontHeight + 1

**Comment by liunianhuaguoyanxi** [comment]
如果单词大于设置的宽度度，它就直接不显示了，而UIKit 一般会显示省略号等，能不能参考UIKit的设计理念，尽量优化下，不然对应固定宽度的视图，服务器传来的数据显示会有问题

**Comment by xiangwangfeng** [comment]
这个可以通过配置 lineBreakMode 和 numberOfLines 就可以实现。
需要注意的 M80AttributedLabel 默认 numberOfLines = 0，而 UILabel 默认为 1。所以看起来的效果就是 UILabel 默认会进行字符缩略。

**Comment by liunianhuaguoyanxi** [comment]
谢了，暂时按回复进行设置了，以后有问题再询问吧
