### ISSUE TITLE
iOS13 默认字体显示异常

### ISSUE THREAD

**Issue by helloworlderly** [xiangwangfeng/M80AttributedLabel#45]
在iOS13中
系统默认字体会变成 Times New Roman。

```
CTFontRef fontRef = CTFontCreateWithName((CFStringRef)font.fontName, font.pointSize, nil);
```
上述代码 font.fontName == ".SFUI-Regular"
fontRef.fontName == "Times New Roman"

iOS13中不能直接使用  "." 开头的字体名。

建议：直接使用UIFont 或者 使用 CTFontCreateWithFontDescriptor

In iOS 13 , system default font changes to "Time New Roman"

```
CTFontRef fontRef = CTFontCreateWithName((CFStringRef)font.fontName, font.pointSize, nil);
```
In view of foregoing, 
font.fontName == ".SFUI-Regular"
fontRef.fontName == "Times New Roman"

Suggestion: You can use UIFont directly or use **CTFontCreateWithFontDescriptor**

**Comment by xiangwangfeng** [comment]
1.9.9 版本已经 fix 了这个问题
