### ISSUE TITLE
关于appendView添加图片问题

### ISSUE THREAD

**Issue by lixiang-8023** [xiangwangfeng/M80AttributedLabel#48]
M80AttributedLabel *label = [[M80AttributedLabel alloc] initWithFrame:CGRectZero];
    for (NSInteger i = 0; i < 3; i++) {
        UIButton *button = [UIButton buttonWithType:UIButtonTypeCustom];
        [button setBackgroundImage:[UIImage imageNamed:@"play"] forState:UIControlStateNormal];
        [button addTarget:self
                   action:@selector(buttonClicked:)
         forControlEvents:UIControlEventTouchUpInside];
        [button setBounds:CGRectMake(0, 0, 30, 30)];
        [button setTag:i];
        [label setText:@"测试示例"];
        [label appendView:button margin:UIEdgeInsetsMake(0, 0, 0, 0) alignment:M80ImageAlignmentCenter];
        NSAttributedString *temp = [[NSAttributedString alloc] initWithString:@"112233"];
        [label setAttributedText:temp];
        }
修改了一下demo的代码，用来模拟我们项目中的需求。先文字再图片再文字，如果按照这种方式添加的话，自定义的图片就会消失。怎么添加才能保证，需求的顺序

**Comment by lixiang-8023** [comment]
如果使用 appendAttributedText 添加的话，cell 重用的时候会反复添加

**Comment by xiangwangfeng** [comment]
cell 重用时可以先 setText:"" 进行内容重置后再 append 即可
